---
title: "preprocess"
output: pdf_document
date: "2023-04-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(reshape2)
library(dslabs)
library(tidyverse)
library(dplyr)
library(ggcorrplot)
library(tidyverse)
library(dplyr)
library(ggcorrplot)
library(lares)
```

```{r}
application_train <- read_csv("./application_train.csv")
head(application_train)
```
```{r}
dim(application_train)
```

```{r}
perc_na <- as.data.frame(round((colSums(is.na(application_train))/nrow(application_train))*100, 2))
perc_na <- perc_na|> rename("perc" = "round((colSums(is.na(application_train))/nrow(application_train)) * 100, 2)")
perc_na
```
```{r}
perc_na$names <- rownames(perc_na)
perc_na
```

```{r}
perc_na_mt_40 <- perc_na |> filter(perc > 40) 
row.names(perc_na_mt_40) <- NULL
perc_na_mt_40
```
```{r}
perc_na_mt_40 <- perc_na_mt_40 |> pivot_wider(
    names_from = names,
    values_from = perc,
  )

perc_na_mt_40 <- as.data.frame(perc_na_mt_40)
perc_na_mt_40
```
```{r}
cols_to_remove <- colnames(perc_na_mt_40)
application_train_drop_na <- select(application_train, setdiff(colnames(application_train), cols_to_remove))
head(application_train_drop_na)
```


```{r}

application_train_zero <-as.data.frame(round((colSums(application_train_drop_na==0, na.rm =T)/nrow(application_train_drop_na))*100,2))
application_train_zero <- application_train_zero |> rename("perc_zero" = "round((colSums(application_train_drop_na == 0, na.rm = T)/nrow(application_train_drop_na)) * 100, 2)")

application_train_zero_90 <- application_train_zero |> filter(perc_zero > 90)
list(rownames(application_train_zero_90))
```
```{r}
application_train_df <- application_train_drop_na |> select(!c("FLAG_EMAIL","FLAG_DOCUMENT_2","FLAG_DOCUMENT_4",             "FLAG_DOCUMENT_5", "FLAG_DOCUMENT_6", "FLAG_DOCUMENT_7", "FLAG_DOCUMENT_8", "FLAG_DOCUMENT_9", "FLAG_DOCUMENT_10", "FLAG_DOCUMENT_11", "FLAG_DOCUMENT_12",   "FLAG_DOCUMENT_13",   "FLAG_DOCUMENT_14",   "FLAG_DOCUMENT_15",  "FLAG_DOCUMENT_16",  "FLAG_DOCUMENT_17", "FLAG_DOCUMENT_18", "FLAG_DOCUMENT_19", "FLAG_DOCUMENT_20" ))
application_train_df
```

```{r}
nums <- application_train_df |> select(where(is.numeric))

```
```{r}
dim(nums)
```

```{r}
corr_cross(nums, # name of dataset
  max_pvalue = 0.05, # display only significant correlations (at 5% level)
  top = 10 # display top 10 couples of variables (by correlation coefficient)
)
```
FLAG_EMP_PHONE, OBS_30_CNT_SOCIAL_CIRCLE, OBS_30_CNT_SOCIAL_CIRCLE, AMT_GOODS_PRICE are removed due to high multicollinearity.
```{r}
application_train_df <- application_train_df|> select(-c(FLAG_EMP_PHONE, OBS_30_CNT_SOCIAL_CIRCLE, OBS_30_CNT_SOCIAL_CIRCLE, AMT_GOODS_PRICE))
head(application_train_df)
```
```{r}

```







